# knowledge_base.py

documents = {
    "disease_agent": [
        "Diabetes is a chronic disease where the body cannot properly regulate blood sugar levels.",
        "Type 1 diabetes is an autoimmune condition where the pancreas produces little or no insulin.",
        "Type 2 diabetes is the most common form, often linked to lifestyle and obesity.",
        "Hypertension means high blood pressure, a major risk factor for heart disease and stroke.",
        "Fever is a temporary rise in body temperature, often a sign of infection or illness.",
        "Blood sugar testing helps monitor and manage diabetes effectively.",
        "Coronavirus is a family of viruses that cause respiratory illnesses ranging from mild to severe.",
        "COVID-19 is caused by the SARS-CoV-2 coronavirus, first identified in 2019.",
        "Common COVID-19 symptoms include fever, cough, fatigue, loss of taste or smell, and breathing difficulty.",
        "Vaccines significantly reduce severe illness, hospitalization, and death from COVID-19.",
        "Cancer is a disease where abnormal cells grow uncontrollably and can invade other tissues.",
        "Cancer can spread to other parts of the body through a process called metastasis.",
        "Common cancer treatments include chemotherapy, radiation therapy, surgery, and immunotherapy.",
        "Early detection of cancer through screening greatly improves treatment outcomes.",
        "Asthma is a chronic lung disease that inflames and narrows the airways.",
        "Alzheimer's disease is a progressive neurological disorder that destroys memory and thinking skills.",
    ],
    "medicine_agent": [
        "Insulin is a hormone produced by the pancreas that helps cells absorb glucose for energy.",
        "Insulin injections or pumps are used by diabetic patients to regulate blood sugar.",
        "Aspirin is a medicine used to reduce pain, fever, and inflammation.",
        "Aspirin is also used in low doses to prevent heart attacks and strokes.",
        "Antibiotics are medicines that kill or slow the growth of bacteria.",
        "Antibiotics only work on bacterial infections, not viral ones like the flu or cold.",
        "Overuse of antibiotics can lead to antibiotic resistance, a serious global health problem.",
        "Vaccines train the immune system to recognize and fight specific pathogens.",
        "Vaccines have eliminated or greatly reduced diseases like polio, smallpox, and measles.",
        "Paracetamol is a common painkiller used to treat mild to moderate pain and reduce fever.",
        "Ibuprofen is an anti-inflammatory drug used for pain, fever, and swelling.",
    ],
    "hospital_agent": [
        "Doctors diagnose illnesses and create treatment plans for patients.",
        "Surgeons are specialist doctors who perform operations to treat diseases or injuries.",
        "Nurses provide daily care for patients, monitor their condition, and assist doctors.",
        "Hospitals provide emergency care, surgeries, diagnostic tests, and inpatient treatment.",
        "A clinic is a smaller medical facility for outpatient consultations and basic treatments.",
        "Pharmacists dispense medications and advise patients on safe and correct drug use.",
        "An ICU (Intensive Care Unit) provides life support and monitoring for critically ill patients.",
        "Emergency rooms treat urgent and life-threatening medical conditions.",
        "Radiologists use imaging techniques like X-rays, MRI, and CT scans to diagnose diseases.",
        "Physiotherapists help patients recover movement and strength after injury or surgery.",
    ],
    "biology_agent": [
        "DNA (Deoxyribonucleic Acid) is a molecule that carries the genetic instructions for all living organisms.",
        "DNA is shaped as a double helix — two strands wound around each other like a twisted ladder.",
        "DNA is made of four chemical bases: Adenine (A), Thymine (T), Guanine (G), and Cytosine (C).",
        "Genes are specific segments of DNA that code for proteins and determine traits.",
        "The human genome contains approximately 3 billion base pairs and around 20,000 genes.",
        "DNA replication is the process where a cell copies its DNA before cell division.",
        "RNA (Ribonucleic Acid) is similar to DNA and acts as a messenger to carry genetic instructions.",
        "Cells are the basic structural and functional units of all living organisms.",
        "The cell nucleus contains DNA and controls cell activity.",
        "Mitochondria are the powerhouses of the cell, producing energy through cellular respiration.",
        "Proteins are large molecules made of amino acids that carry out most functions in the body.",
        "Proteins are built by ribosomes following instructions coded in DNA.",
        "Enzymes are special proteins that speed up chemical reactions in the body.",
        "Photosynthesis is the process by which plants use sunlight, water, and CO2 to make glucose.",
        "Cell division (mitosis) produces two identical daughter cells for growth and repair.",
        "Meiosis is a type of cell division that produces reproductive cells (sperm and egg).",
        "Mutations are changes in DNA sequence that can affect how genes work.",
        "CRISPR is a revolutionary gene-editing technology that can modify DNA sequences precisely.",
    ],
    "nutrition_agent": [
        "Protein is an essential macronutrient that helps build and repair muscles and tissues.",
        "Good sources of protein include meat, fish, eggs, dairy, legumes, and nuts.",
        "Carbohydrates are the body's primary energy source, found in grains, fruits, and vegetables.",
        "Complex carbohydrates like whole grains digest slowly and provide sustained energy.",
        "Fats are essential for hormone production, brain function, and absorption of fat-soluble vitamins.",
        "Healthy fats include omega-3 fatty acids found in fish, flaxseed, and walnuts.",
        "Vitamins are organic compounds the body needs in small amounts for normal function.",
        "Vitamin C supports the immune system and is found in citrus fruits and vegetables.",
        "Vitamin D is essential for bone health and is produced when skin is exposed to sunlight.",
        "Minerals like calcium, iron, and zinc are vital for bones, blood, and enzyme function.",
        "Fiber aids digestion, controls blood sugar, and lowers cholesterol.",
        "Water makes up about 60% of the human body and is essential for every bodily function.",
        "A balanced diet includes proteins, carbohydrates, healthy fats, vitamins, minerals, and water.",
    ]
}